drain script shouldn't fail when there is a stale HAPRroxy pid in pidfile
cloudfoundry/haproxy-boshrelease pull request #322
Opened 2022-09-12 15:39 UTC by kecirlotfi

We encountered an issue during deployment phase. Bosh filed to drain on canary VM. 
```
Task 6224192 | 23:51:20 | L executing pre-stop: ha_proxy_z2/16e2782c-adcd-4e88-b5b4-e064c9911c57 (0) (canary)
Task 6224192 | 23:51:20 | L executing drain: ha_proxy_z2/16e2782c-adcd-4e88-b5b4-e064c9911c57 (0) (canary) (00:00:03)
                        L Error: Action Failed get_task: Task b5e5ccc7-02af-4fc6-508c-f31d95f95749 result: 1 of 2 drain scripts failed. Failed Jobs: haproxy. Successful Jobs: syslog_forwarder.
Task 6224192 | 23:51:22 | Error: Action Failed get_task: Task b5e5ccc7-02af-4fc6-508c-f31d95f95749 result: 1 of 2 drain scripts failed. Failed Jobs: haproxy. Successful Jobs: syslog_forwarder.

Task 6224192 Started  Tue Aug 23 23:50:51 UTC 2022
Task 6224192 Finished Tue Aug 23 23:51:22 UTC 2022
Task 6224192 Duration 00:00:31
Task 6224192 error
Updating deployment:
  Expected task '6224192' to succeed but state is 'error'

Exit code 1

[bosh][INFO] Deprovisioning client 'd.haproxy.deploy.9b17b2'...
error: lifecycle 'deploy' for deployment 'haproxy' failed in action 'deploy'. Action output (can be empty):

exit status 1
```
After running investigation on the canary VM, we noticed that the drain script fails because the file `/var/vcap/sys/run/bpm/haproxy/haproxy.pid` still exists and non empty. 

The script checks the existence of the pidfile and reads its content then kill the child process that belongs the PID read from the pidfile. 

As the file exists and not empty, `haproxy_wrapper_pid=$(pgrep -P "$pid" haproxy_wrapper)` fails with exit code `1` (process doesn't exist), which makes fail the script.

With the fix we propose, `haproxy_wrapper_pid=$(pgrep -P "$pid" haproxy_wrapper || true)`, awe handle the case of a crashed haproxy_wrapper parent process when its pidfile still exists.

2022-09-14 16:11 UTC, plowin commented
Hi @kecirlotfi , please try rebasing this to the current master, we had some issues with the CI which should be good now!

2022-09-14 16:21 UTC, plowin commented on spec/haproxy/templates/drain_spec.rb
> +            # In case haproxy_wrapper process is stale, pid_exists will be empty,
There is no variable named `pid_exists`, like this, the comment is not very useful to me

2022-09-15 06:15 UTC, peanball commented
@kecirlotfi please keep this in Draft state until you're ready for it to be reviewed.

2022-09-15 09:32 UTC, domdom82 requested changes

2022-09-15 09:32 UTC, domdom82 commented on acceptance-tests/drain_test.go
> +		By("Waiting monit to report HAProxy is now healthy (due to having a healthy backend instance)")
```suggestion
		By("Waiting for monit to report HAProxy is now healthy (due to having a healthy backend instance)")
```

2022-09-15 09:32 UTC, domdom82 commented on acceptance-tests/drain_test.go
> +		By("Draining HAproxy, drain script should not fail and HAproxy should still healthy")
```suggestion
		By("Draining HAproxy, drain script should not fail and HAproxy should still be healthy")
```

2022-09-15 09:32 UTC, domdom82 commented on jobs/haproxy/templates/drain.erb
> +if [ "${pid_exists}" = '' ]; then
```suggestion
if ! ps -p ${pid} > /dev/null; then
```

2022-09-15 09:32 UTC, domdom82 commented on jobs/haproxy/templates/drain.erb
> +  echo "$(date): There was no process for the recorded haproxy_wrapper PID." >> ${logfile}
```suggestion
  echo "$(date): There was no process for the recorded haproxy_wrapper PID (${pid})." >> ${logfile}
```

2022-09-15 09:33 UTC, domdom82 commented on jobs/haproxy/templates/drain.erb
> +if [ "${pid_exists}" = '' ]; then
as discussed

2022-09-15 12:55 UTC, domdom82 commented on spec/haproxy/templates/drain_spec.rb
> +          if ![ ps -p ${pid} >/dev/null ]; then
this doesn't work.
```
if ! ps -p ${pid} >/dev/null; then
```
you need to lose the brackets as this is not a test anymore. you are now executing a program and testing for its exit code.

2022-09-15 12:56 UTC, domdom82 commented on spec/haproxy/templates/drain_spec.rb
> +            if ![ ps -p ${pid} >/dev/null ]; then
```
if ! ps -p ${pid} >/dev/null; then
```

2022-09-15 14:42 UTC, kecirlotfi commented on spec/haproxy/templates/drain_spec.rb
> +            if ![ ps -p ${pid} >/dev/null ]; then
Fixed. Thanks 👍

2022-09-15 15:40 UTC, domdom82 approved these changes

2022-09-15 16:10 UTC, merged