ci: update version file for releases
cloudfoundry/haproxy-boshrelease pull request #551
Opened 2023-10-25 06:46 UTC by b1tamara

2023-10-25 06:58 UTC, maxmoehl requested changes

2023-10-25 06:58 UTC, maxmoehl commented on haproxy-boshrelease.tgz
Please be careful about what you check in!

2023-10-25 08:50 UTC, b1tamara commented on haproxy-boshrelease.tgz
oh good point

2023-10-26 08:30 UTC, maxmoehl approved these changes

2023-10-26 08:35 UTC, merged